services:
  todolist-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todolist-back
    ports:
      - 4000:4000
    volumes:
      - ./backend/db/:/app/db
    env_file:
      - ./backend/.env
  todolist-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todolist-web
    ports:
      - 3000:3000